externalDatabase:
  type: postgres
  host: ${db_host}
  port: ${db_port}
  database: ${db_schema}
  user: ${db_user}
  password: ${db_password}

airflow: 
  users:
    - username: ${airflow_username}
      password: ${airflow_password}
      role: ${airflow_role}
      email: ${airflow_email}
      firstName: ${airflow_firstname}
      lastName: ${airflow_lastname}

web:
  service:
    type: LoadBalancer
    externalPort: 8080

ingress:
  enabled: true
  web:
    host: ${lb_host}
    path: "/"
    tls:
      enabled: true
      secretName: ${secret_name}

serviceAccount:
  create: false
  name: ${service_account_name}
  annotations: 
    eks.amazonaws.com/role-arn: ${eks_oidc_arn}

postgres:
  enabled: true
  image:
    registry: ghcr.io
    repository: airflow-helm/postgresql-bitnami
    tag: 11.16-patch.0
    pullPolicy: IfNotPresent
  postgresqlDatabase: airflow
  postgresqlUsername: postgres
  postgresqlPassword: ${db_password}
  persistence:
    enabled: true
    storageClass: ${storage_class}
    accessModes:
      - ReadWriteMany
    size: 5Gi
