webserver:
  readinessProbe:
    initialDelaySeconds: 500
    periodSeconds: 40

  livenessProbe:
    initialDelaySeconds: 500
    periodSeconds: 40

  startupProbe:
    timeoutSeconds: 200
    periodSeconds: 40
  waitForMigrations:
    enabled: false

redis:
  persistence: 
    size: 10Gi
    storageClassName: ${svc_name}

data:
  persistence: 
    size: 10Gi
    storageClassName: ${svc_name}


logs:
  persistence:
    enabled: true
    storageClassName: ${svc_name}
    existingClaim: ${pvc_name}

scheduler:
  waitForMigrations:
    enabled: false

pgbouncer:
  enabled: true

