webserver:
  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: ${service_account_name}
  defaultUser:
    enabled: false
    username: ${airflow_username}
    password: ${airflow_password}
    role: ${airflow_role}
    email: ${airflow_email}
    firstName: ${airflow_firstname}
    lastName: ${airflow_lastname}
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080
        nodePort: 30050


dags:
  persistence:
    enabled: true
    storageClassName: ${storage_class_name}
    accessMode: ReadWriteMany
    existingClaim: ${pvc_name}

logs:
  persistence:
    enabled: true
    storageClassName: ${storage_class_name}
    existingClaim: ${pvc_name}

redis:
  enabled: true

pgbouncer:
  enabled: true

triggerer:
  serviceAccount:
    create: false
    name: ${service_account_name}
  persistence:
    storageClassName: ${storage_class_name}

data:
  metadataConnection:
    protocol: postgresql
    host: ~
    port: 5432
    db: postgres
    user: postgres
    pass: postgres

