webserver:
  readinessProbe:
    initialDelaySeconds: 500
    periodSeconds: 40

  livenessProbe:
    initialDelaySeconds: 500
    periodSeconds: 40

  startupProbe:
    timeoutSeconds: 200
    periodSeconds: 40
  waitForMigrations:
    enabled: false
  # service:
  #   type: NodePort
  #   ports:
  #     - name: airflow-ui
  #       port: 8080
  #       targetPort: 8080
  #       nodePort: 30050
  #   type: NodePort
  #   ports:
  #     - name: airflow-ui
  #       port: 8080
  #       targetPort: 8080
  #       nodePort: 30050
data:
  metadataConnection:
    user:  ${db_user}
    pass:   ${db_password}
    protocol: postgresql
    host: ${db_host}
    port: 5432
    db: ${db_name}

redis:
  persistence: 
    enabled: false
    #size: 10Gi
    #storageClassName: ${svc_name}


workers:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ${svc_name}
  waitForMigrations:
    enabled: false



triggerer:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ${svc_name}
  waitForMigrations:
    enabled: false   


# logs:
#   persistence:
#     enabled: true
#     storageClassName: ${svc_name}
#     existingClaim: ${pvc_name}

scheduler:
  waitForMigrations:
    enabled: false

pgbouncer:
  enabled: true

postgresql:
  enabled: false
